### ISSUE TITLE
add @Listen decorator 

### ISSUE THREAD

**Issue by aelbore** [geocine/custom-elements-ts#10]
- Decorator: @Listen
- params: 
  - eventName: i.e click, change
  - selector: if selector is not define default would be self/this.
       - this is the target element

**Comment by geocine** [comment]
I propose the format would be something like this:

### shorthand

`<selector>:<event>`

eg. 

`@Listen('input:click')`

### long version

for longer css queries 

`@Listen('click','input[name="email"]'); `

or 

`@Listen('{input[name="email"}:click')`

just some suggestions

**Comment by aelbore** [comment]
Pull Request Reference
#22

**Comment by geocine** [comment]
Thanks! 👍
