### ISSUE TITLE
please be clear if scss/sass can realy be used.

### ISSUE THREAD

**Issue by dkipp** [geocine/custom-elements-ts#51]
well done, I was searching something like this.
Your examples are using xyz.scss for the style files. This is awesome, because it made me think that a css preprocessor (sass) was supported out of the box. But looking at the code in more detail it seems like I'a wrong.

So whats the state here? is it supported, was it supported and the filename is the last witness. Or will it be supported in future updates and the filename is a sneak peek?

I'm hoping for the sneak peek ;-)

**Comment by geocine** [comment]
It is supported , I wonder what issue you are facing. The rollup build step handles the scss files.

**Comment by dkipp** [comment]
It works now, don't know what I did wrong.

I had to solve some errors with the dependencies, looks like: @ngx-devtools/common is required but not listed in package.json
